### ISSUE TITLE
how to read mw100?

### ISSUE THREAD

**Issue by yanzixiang** [evopro-ag/Sharp7Reactive#1]
how to read mw100?

**Comment by fbarresi** [comment]
Hi!

if I correctly understand your question, you whould like to read a MW (Memory Word) from a PLC.

This library just offers some reactive methods for Sharp7 and it is actually limited to read and write operations for datablocks.

If you want to read (or even write) markers you should directly use Sharp7.

Please see the wiki for this operation under: https://github.com/fbarresi/Sharp7/wiki/IO-functions#ReadArea

**Comment by yanzixiang** [comment]
> This library just offers some reactive methods for Sharp7 and it is actually limited to read and write operations for datablocks.

Why do you limit this ?
you can just make the S7VariableAddress class public,
and let users use it.

**Comment by fbarresi** [comment]
This is a great Idea!
Please submit a pull request for that!

**Comment by yanzixiang** [comment]
> This is a great Idea!
> Please submit a pull request for that!

https://github.com/evopro-ag/Sharp7Reactive/pull/2
