### ISSUE TITLE
Performance compared to Sharp7 legacy version?

### ISSUE THREAD

**Issue by lio94** [evopro-ag/Sharp7Reactive#7]
Would I see performance or robustness improvement in communication (with a newer, powerful S7 model) when using this instead of Sharp7 only? Are there benchmarks where these would be compared?

**Comment by Peter-B-** [comment]
Hi,

Sharp7Reactive is a wrapper around Sharp7. So it can never outperform Sharp7.

Having said that, Sharp7Reactive uses some advanced features of Sharp7, like reading multiple variables in one go, and has seen some substantial performance improvements with the latest 2.0 release. So if you are considering performance, you might want to take a look at this implementation.

Kind regards
Peter
