### ISSUE TITLE
Sharp7Plc disconnection

### ISSUE THREAD

**Issue by fgbustoa** [evopro-ag/Sharp7Reactive#8]
How to properly disconnect/dispose Sharp7Plc object ?

I tried Dispose(), but it seems to hang indefinetely ...

Thanks

**Comment by fbarresi** [comment]
Hi!
Can you please post a snippets of your code or an example?

The public Dispose method should work: it closes the connection if opened and releases all the resources.

Best regards,
FB

**Comment by fgbustoa** [comment]
Here it is (it's a WinForms project, .NET 8.0 targeting):

public partial class FrmMain : Form
{

	...
	...
	...

        private Sharp7Plc? PLC;
        private CompositeDisposable disposables = new ();

	...
	...
	...

        private async void btnConnect_Click(object sender, EventArgs e)
        {
            Cursor = Cursors.WaitCursor;
            try
            {
                PLC = new Sharp7Plc("127.0.0.1", 0, 0);
                disposables.Add(PLC);
                await PLC.TriggerConnection();
                await PLC.ConnectionState.FirstAsync(c => c == Sharp7.Rx.Enums.ConnectionState.Connected).Timeout(new TimeSpan(0, 0, 0, 0, 3000)).ToTask();
            }
            catch (Exception Err)
            {
                AddToLog("Error connecting to server: " + Err.Message);
            }
            finally
            {
                Cursor = Cursors.Default;
            }
        }

        private void btnDisconnect_Click(object sender, EventArgs e)
        {
            PLC.Dispose();
        }

	...
	...
	...
}

**Comment by fbarresi** [comment]
Hi!
Thanks for sharing this snippets.

It seems pretty straight forward to me.

So actually, the dispose method in sharp7Rx calls and wait for the disconnect to be finished. The disconnect method is a simple `socket.close()` without any other logic in it.

This close operation doesn't produce any wait time in general, but there are some cases, where a socket can hand in `CLOSE_WAIT` state for example if you try to close a socket multiple times or sometimes when you try to read after the socket get closed.

Could you please check your code for such cases?

Thanks,
FB

**Comment by fgbustoa** [comment]
At the end, i think that the executed disposing code is this one:

public class Sharp7Plc : IPlc
{
	...
	...
	...

    public void Dispose()
    {
        Dispose(true);
        GC.SuppressFinalize(this);
    }
	...
	...
	...

    protected virtual void Dispose(bool disposing)
    {
        if (disposed) return;
        disposed = true;

        if (disposing)
        {
            notificationSubscription?.Dispose();
            notificationSubscription = null;

            if (s7Connector != null)
            {
                s7Connector.Disconnect().Wait();
                s7Connector.Dispose();
                s7Connector = null;
            }

            multiVariableSubscriptions.Dispose();
        }
    }
	...
	...
	...
}

Perhaps is it blocking into "s7Connector.Disconnect().Wait();" ???

**Comment by fbarresi** [comment]
Yes, this is exactly what I meant.
If you continue to decompile and navigate to the method definition, you will found a socket.Close();

**Comment by fgbustoa** [comment]
Unfortunately i cannot debug into this part of code, to see which line is blocking .... (or better .... i have no idea on how to debug it !!!)

Do you think that targeting .NET 8.0 could be the problem ??? I saw taht Sharp7.Rx targets 6.0 .......

**Comment by fbarresi** [comment]
No, this doesn't play any role at all.

Did you already check in your code if you call the dispose twice or read after dispose?

Alternatively you could place a breakpoint on the dispose and look on the socket state before you attempt the dispose.

**Comment by fgbustoa** [comment]
On server side (Snap7) the "ClientsCount" property still remain = 1.

It means i never reached socket.close()

ANOTHER QUESTION:
Since i need to do "disposables.Add(PLC)" on connection open .....
.... i need to call "disposables.Dispose()" on connection close ??? I tried, and also this commend hangs ....

**Comment by fgbustoa** [comment]
Non vorrei approfittare della tua disponibilità, ma potrei passarti i miei progetti client & server per dargli una veloce occhiata.
I wouldn't want to take advantage of your availability, but I could pass you my client & server projects to give them a quick look.

In any case, thanks for your support !!!

**Comment by fgbustoa** [comment]
Sorry !!! My mistake !!!
Errata corrige: when my client is stuck in PLC.Dispose(), server program shows "ClientsCount" passing from 1 to 0.
It means that i reach "s7Connector.Disconnect().Wait()" (at least the "Disconnect" part of the code ...)

**Comment by fbarresi** [comment]
Si, se puoi mandami tutto che gli do un'occhiata e facciamo prima. 😉
Mail: f**e.ba**esi@gmail.com (sostituisci: e, d ed r agli asterischi)

**Comment by fgbustoa** [comment]
Intanto grazie 1000 per la tua disponibilità.

Non vedo però alcun asterisco nella tua email ....

CIAO

[cid:905eeb36-5e8d-4971-8cd7-f209fd6630a3]

________________________________
Da: Federico Barresi ***@***.***>
Inviato: giovedì 17 ottobre 2024 07:08
A: evopro-ag/Sharp7Reactive ***@***.***>
Cc: Fabio Grassi ***@***.***>; Author ***@***.***>
Oggetto: Re: [evopro-ag/Sharp7Reactive] Sharp7Plc disconnection (Issue #8)


Si, se puoi mandami tutto che gli do un'occhiata e facciamo prima. 😉
Mail: ***@***.******@***.***> (sostituisci: e, d ed r agli asterischi)

**Comment by fbarresi** [comment]
Si, se puoi mandami tutto che gli do un'occhiata e facciamo prima. 😉
Mail: f**e.ba**esi@gmail.com (sostituisci: e, d ed r agli asterischi)

**Comment by fbarresi** [comment]
Look in github

**Comment by fgbustoa** [comment]
Ho visto ... sono un coglione.

Ecco un piccolo programmino scemo in WinForms .NET 6.0. E' un form con 2 bottoni: CONNETTI e DISCONNETTI, sufficienti a riprodurre il problema.

[https://res.cdn.office.net/assets/mail/file-icon/png/zip_16x16.png]WinFormsApp1.zip<https://sipisrlit-my.sharepoint.com/:u:/g/personal/fabio_grassi_sipi_it/EVLrlseKr41Ho7oEMLVV7QcBAXmt--4R9vN9NKY3gH8-Bg?e=hCcb4j>


Devi solo cambiare l'IP del server, che è hard-coded.

P.S.:
Lato server c'è il tuo Snap7 Server. Non ho mai provato con un PLC reale, ma non credo che influenzi la cosa ...

CIAO & GRAZIE

________________________________
Da: Federico Barresi ***@***.***>
Inviato: giovedì 17 ottobre 2024 08:28
A: evopro-ag/Sharp7Reactive ***@***.***>
Cc: Fabio Grassi ***@***.***>; Author ***@***.***>
Oggetto: Re: [evopro-ag/Sharp7Reactive] Sharp7Plc disconnection (Issue #8)


Look in github

**Comment by fbarresi** [comment]
Ok! 
I analyzed your project and I can already tell you, that due to the use of async operations in the main thread you reached a deadlock.

So, now is clear: there is no problem with the library.

In my next post you'll find the extended solution/explanation with some comments.

FB

**Comment by fbarresi** [comment]
## Fixing up your code

The deadlock consist on having a async task triggered directly on the main thread. 
You can imagine this in the call stack of the program like a list of actions: when you click a button a new action is added to the stack and in order to focus again to the window a second one is even added __AFTER that__ to return back to main window. However the disconnect action is async and will act like producing a new action on stack.  So you basically have such actions in your execution stack:

- Main Program
 - Disconnect Action
- Return to Main Program
 - wait for Disconnect

Of course the `Return to Main Program` can execute only after the `Disconnect` is completed. But the Disconnect could add its awaiter only at the end of the stack: this is the Deadlock.

## Run stuff in Background

The trick is running actions in background and not in the main thread (Welcome to the 21st Century 😅)
I modified your code in order to running in the disconnect thread in background and added a bit of logging for better visualize the story:

```csharp
private async void button1_Click(object sender, EventArgs e)
{
    Console.WriteLine("Creating PLC...");
    PLC = new Sharp7Plc("127.0.0.1", 0, 0);
    // establish connection
    Console.WriteLine("Connecting...");
    await PLC.TriggerConnection();
    // wait for connection to be established
    var state = await PLC.ConnectionState.FirstAsync(c => c == Sharp7.Rx.Enums.ConnectionState.Connected).Timeout(new TimeSpan(0, 0, 0, 0, 3000)).ToTask();
    Console.WriteLine($"connection state: {state}");
}

private async void button2_Click(object sender, EventArgs e)
{
    Console.WriteLine("Disconnecting...");
    await Task.Run(() => PLC.Dispose()).ConfigureAwait(false);
    Console.WriteLine("PLC disposed!");
}
```

As you can see: we now run the `PLC.Dispose()` in an own task and we tell the call stack, that this should please not produce any deadlock with `.ConfigureAwait(false)`

Here is how it ran:

![winform1](https://github.com/user-attachments/assets/384e8dc3-18f5-4cc0-804e-ac544d31da37)

As you can see: no application freezing, no hanging, a quite clean dispose at glance here. 

## My personal consideration and hints for you

- try to avoid WinForms,  WPF is much better
- try to avoid `async void` functions or you might be unable to catch errors when stuff runs in background. 
 there are good frameworks like [ReactiveUI](https://www.reactiveui.net/) that helps you a lot
- you might want to move the logic of managing PLCs outside of your visualization layer: how about introducing a PLC provider like this?
```csharp
public interface IPlcProvider
{
    IPlc CreatePlc(string name, string ipAddress, int rack, int slot);
    IPlc GetPlc(string name);
    Task<bool> RemovePlc(string name);
}

public class PlcProvider : IDisposable, IPlcProvider
{
    public readonly Dictionary<string, IPlc> plcs = new();
    public IPlc CreatePlc(string name, string ipAddress, int rack, int slot)
    {
        RemovePlc(name);

        var sharp7Plc = new Sharp7Plc(ipAddress, rack, slot);
        sharp7Plc.InitializeConnection();
        plcs.Add(name, sharp7Plc);
        return plcs[name];
    }

    public IPlc GetPlc(string name)
    {
        if (plcs.TryGetValue(name, out var plc))
        {
            return plc;
        }
        throw new KeyNotFoundException();
    }

    public async Task<bool> RemovePlc(string name)
    {
        if (plcs.TryGetValue(name, out var plc))
        {
            await Task.Run(() => plc.Dispose()).ConfigureAwait(false);
            plcs.Remove(name);
        }

        return true;
    }

    public void Dispose()
    {
        foreach (var plc in plcs.Values)
            plc.Dispose();
    }
}
```

**Comment by fgbustoa** [comment]
Thanks for all your support and suggestions !!!

**Comment by fbarresi** [comment]
@aseminjakiw please close this issue as solved.
