### ISSUE TITLE
[WPF] Connection to PLC hangs

### ISSUE THREAD

**Issue by sekulicb** [evopro-ag/Sharp7Reactive#9]
Following simple example on how to use this library I have ViewModel that calls my service which connects to PLC

![image](https://github.com/user-attachments/assets/d4caedf9-800a-45fe-ba0a-8b7da757b942)

and my service for PLC:

![image](https://github.com/user-attachments/assets/7f1bf0a3-7458-4bf9-acd4-eb10854a18d0)

It never reaches breakpoint to check if the PLC is actually connected. What am I doing wrong ?

**Comment by fbarresi** [comment]
Hi! 

On my first impression it seems really similar to #8 .

Did you check the solution provided [here](https://github.com/evopro-ag/Sharp7Reactive/issues/8#issuecomment-2424170692)?

**Comment by sekulicb** [comment]
Hi @fbarresi As you can see from the code mentioned in issue #8 :

 // wait for connection to be established
var state = await PLC.ConnectionState.FirstAsync(c => c == Sharp7.Rx.Enums.ConnectionState.Connected).Timeout(new TimeSpan(0, 0, 0, 0, 3000)).ToTask();
Console.WriteLine($"connection state: {state}");

Your code actually prints "connection state: connected" on the screen. My code never reaches the state where connection is established. I tried on machine where PLC is connected and also on other PC that doesn't have PLC. I was expecting for the library to throw exception, or to connect at some point ?

**Comment by fbarresi** [comment]
Hi! 

Yes, the code in the previous issue returns a connection state if the connection can be established within the given time or throws an exception instead.

However in your example you do not have any timeout constraint, so the function will wait until the the plc reaches the state  connected. 

BTW: you wrote `using var disposables = new CompositeDisposable();` that means, that this disposable will be disposed once out of scope. So once the InitializeAsync method completed, your plc will be disposed. It definitely does not make any sense to me to return a value for initialization that refers to an already disposed PLC 😅.

Please send your code I will debug it and report to you as soon as possible. 

Best regards,
FB

**Comment by sekulicb** [comment]
Hi.

I added timeout constraint yesterday, but since all it does, it just freezes entire UI, I removed it. There is no exception after timeout constraint expires.
![image](https://github.com/user-attachments/assets/42886959-e11e-4da6-8fc5-39964d9bf8fc)

using var disposables = new CompositeDisposable(); 

Yes that is true, but there is a breakpoint before methods exits, so I should be good. I just wanted to verify connection, to my defence 😄 Didn't think that far ahead.

Okay, I will have to create a small repro then. Will let you know

[Update]
Just wanted to update, there is Exception thrown: 'System.TimeoutException' in System.Private.CoreLib.dll but only in output terminal, doesn't get caught in catch block

**Comment by fbarresi** [comment]
Ok, when the whole ui freezes is that a simptom that your application ran into a deadlock (like in #8) .

You can also simply attach the important files or a zipped folder here in the issue, I can generate a project around them in my own.

Best regards,
FB

**Comment by sekulicb** [comment]
Okay I figured it out, now it throws the exception. The trick is to add ConfigureAwait(false) at the end, so it should look like this:

`var connState = await _plc.ConnectionState
    .FirstAsync(c => c == ConnectionState.Connected)
    .Timeout(new TimeSpan(0, 0, 0, 2))
    .ToTask().ConfigureAwait(false);`

**Comment by fbarresi** [comment]
Awesome! 

Thanks for share your solution. 

Different simptoms, but still same problem. 😉

> As you can see: we now run the `PLC.Dispose()` in an own task and we tell the call stack, that this should please not produce any deadlock with `.ConfigureAwait(false)`

**Comment by sekulicb** [comment]
Hi. Just wanted to thank you again for your quick input and help, I managed to connect to PLC, all works as expected.
